// Generated by Wrangler on Sat Aug 10 2024 15:40:04 GMT+0530 (India Standard Time)
// by running `wrangler types`

interface Env {
	MY_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").MyDurableObject>;
	AI: Ai;
}
